
Proj6: main.o BinaryNodeTree.o BinarySearchTree.o BinaryTreeInterface.o BinaryNode.o IntBinarySearchTree.o NotFoundException.o PrecondViolatedExcep.o 
	g++ -std=c++11 main.o BinaryNodeTree.h BinarySearchTree.h BinaryTreeInterface.h BinaryNode.h IntBinarySearchTree.h NotFoundException.h PrecondViolatedExcep.h 

main.o: main.cpp
 
	g++ -std=c++11 -c main.cpp

BinaryNodeTree.o: BinaryNodeTree.h
 
	g++ -std=c++11 -c BinaryNodeTree.h

BinarySearchTree.o: BinarySearchTree.h

	g++ -std=c++11 -c BinarySearchTree.h

BinaryTreeInterface.o: BinaryTreeInterface.h

	g++ -std=c++11 -c BinaryTreeInterface.h

BinaryNode.o: BinaryNode.h

	g++ -std=c++11 -c BinaryNode.h

IntBinarySearchTree.o: IntBinarySearchTree.h

	g++ -std=c++11 -c IntBinarySearchTree.h

NotFoundException.o: NotFoundException.h

	g++ -std=c++11 -c NotFoundException.h

PrecondViolatedExcep.o: PrecondViolatedExcep.h

	g++ -std=c++11 -c PrecondViolatedExcep.h


clean:

	rm -rf *.o Proj6





