
Proj8: main.o Graph.o Graph2.o GraphInterface.o GraphNode.o GraphNode2.o NodeQueue.o NodeQueue2.o
	g++ -std=c++11 main.o Graph2.o Graph.h GraphInterface.h GraphNode.h GraphNode2.o NodeQueue.h NodeQueue2.o

main.o: main.cpp
 
	g++ -std=c++11 -c main.cpp

Graph.o: Graph.h
 
	g++ -std=c++11 -c Graph.h

Graph2.o: Graph2.cpp
 
	g++ -std=c++11 -c Graph2.cpp

GraphInterface.o: GraphInterface.h
 
	g++ -std=c++11 -c GraphInterface.h

GraphNode.o: GraphNode.h
 
	g++ -std=c++11 -c GraphNode.h

GraphNode2.o: GraphNode2.cpp
 
	g++ -std=c++11 -c GraphNode2.cpp

NodeQueue.o: NodeQueue.h
 
	g++ -std=c++11 -c Graph.h

NodeQueue2.o: NodeQueue2.cpp
 
	g++ -std=c++11 -c NodeQueue2.cpp


clean:

	rm -rf *.o Proj8





